name: CD
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  cd_ubuntu_x86_64:
    runs-on: ubuntu-latest
    env:
      OUTPUT: tools.tar.gz
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3
          python3 -m pip install --user zstandard
          python3 -m pip install --user ordered-set
          python3 -m pip install --user Nuitka
      - name: Build applications
        run: |
          python3 -m nuitka --standalone --onefile --include-package-data=freesansbold.ttf --assume-yes-for-downloads "colour swizzler.py"
          python3 -m nuitka --standalone --onefile --include-package-data=freesansbold.ttf --assume-yes-for-downloads "ship name tool.py"
      - name: Package tools
        run: tar -czf ${{ env.OUTPUT }} colour\ swizzler.* ship\ name\ tool.* README.md LICENSE
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}

  cd_windows_win64:
    runs-on: windows-latest
    env:
      OUTPUT: tools.zip
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --user zstandard
          python -m pip install --user ordered-set
          python -m pip install --user Nuitka
      - name: Build applications
        run: |
           python -m nuitka --standalone --onefile --include-package-data=freesansbold.ttf --assume-yes-for-downloads "colour swizzler.py"
           python -m nuitka --standalone --onefile --include-package-data=freesansbold.ttf --assume-yes-for-downloads "ship name tool.py"
      - name: package tools
        run: 7z a ${{ env.OUTPUT }} colour\ swizzler.* ship\ name\ tool.* README.md LICENSE
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}
